name: UpdateConfigs
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"

jobs:
  UpdateConfigs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies (Bun)
        working-directory: ./core-parser-ts
        run: bun install

      - name: Run index.ts (Сборщик)
        working-directory: ./core-parser-ts
        run: bun index.ts

      - name: Commit Changes
        run: |
          git config --local user.name "Stella-Blondie"
          git config --local user.email "stella@blondie.ai"
          
          # Добавляем ВСЕ новые папки и файлы, которые нагенерил скрипт
          git add core-parser-ts/category/protocols/*.txt
          git add core-parser-ts/category/countries/*.txt
          git add core-parser-ts/category/networks/*.txt
          git add core-parser-ts/category/*.txt
          git add core-parser-ts/white-list_available.txt
          
          git commit -m "🚀 Stella: Syncing ALL protocols (Reality, Hys2, TUIC) ✨" || exit 0
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}