name: UpdateConfigs
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"

jobs:
  UpdateConfigs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies (Bun)
        working-directory: ./core-parser-ts
        run: bun install

      - name: Run index.ts (Сборщик)
        working-directory: ./core-parser-ts
        run: bun index.ts

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Requests 📦
        # Вот эта строчка спасет нас от ошибки!
        run: pip install requests python-dotenv

      - name: Run Stealth Validator
        run: python ./network-validator/checker_v3.py --input ./core-parser-ts/Protocols/vless.txt --output ./core-parser-ts/white-list_available.txt

      - name: Commit Changes
        run: |
          git config --local user.name "Stella-Blondie"
          git config --local user.email "stella@blondie.ai"
          git add .
          git commit -m "🎯 Stella: Fixed ModuleNotFoundError & Updated Deps ✨" || exit 0
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}